#!groovy

def buildVersion = "1.0.4"
def projectName = "intyg-infrastructure-directory-privatepractitioner-terms-schemas"
stage('checkout') {
    node {
        util.run { checkout scm }
    }
}

stage('build') {
    node {
        shgradle "--refresh-dependencies :${projectName}:clean :${projectName}:build -DbuildVersion=${buildVersion}"
    }
}

stage('tag and upload') {
    node {
        shgradle ":${projectName}:uploadArchives :${projectName}:tagRelease -DbuildVersion=${buildVersion}"
    }
}
