#!groovy

def buildVersion = "2.1.1"
def projectName = "schemas-support"
stage('checkout') {
    node {
        util.run { checkout scm }
    }
}

stage('build') {
    node {
        shgradle "--refresh-dependencies :${projectName}:clean :${projectName}:build -DbuildVersion=${buildVersion}"
    }
}

stage('tag and upload') {
    node {
        shgradle ":${projectName}:uploadArchives :${projectName}:tagRelease -DbuildVersion=${buildVersion}"
    }
}
