<?xml version="1.0" encoding="UTF-8" ?>
<!--
  ~ Copyright (C) 2019 Inera AB (http://www.inera.se)
  ~
  ~ This file is part of sklintyg (https://github.com/sklintyg).
  ~
  ~ sklintyg is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ sklintyg is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with this program.  If not, see <http://www.gnu.org/licenses/>.
  -->
<wsdl:definitions name='GetCertificateAdditionsInteraction' xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/' xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/' xmlns:xs='http://www.w3.org/2001/XMLSchema' xmlns:tjsr='urn:riv:clinicalprocess:healthcond:certificate:GetCertificateAdditionsResponder:1' xmlns:tjsi='urn:riv:clinicalprocess:healthcond:certificate:GetCertificateAdditionsInitiator:1' xmlns:tns='urn:riv:clinicalprocess:healthcond:certificate:GetCertificateAdditions:1:rivtabp21' targetNamespace='urn:riv:clinicalprocess:healthcond:certificate:GetCertificateAdditions:1:rivtabp21' xmlns:itr='urn:riv:itintegration:registry:1'>
  <wsdl:documentation>
		Tjänsteinteraktionens namn: GetCertificateAdditionsInteraction
		Beskrivning: 
		  Hämta kompletteringar knutna till ett viss intyg
		Revisioner: 
		Tjänstedomän: clinicalprocess:healthcond:certificate
		Tjänsteinteraktionstyp: Fråga-Svar
		WS-profil: RIVTABP21
		Förvaltas av: Sveriges Kommuner och Landsting
		</wsdl:documentation>
  <wsdl:types>
    <xs:schema targetNamespace='urn:riv:clinicalprocess:healthcond:certificate:GetCertificateAdditions:1:rivtabp21'>
      <xs:import schemaLocation='GetCertificateAdditionsResponder_1.0.xsd' namespace='urn:riv:clinicalprocess:healthcond:certificate:GetCertificateAdditionsResponder:1' />
      <xs:import schemaLocation='../../core_components/itintegration_registry_1.0.xsd' namespace='urn:riv:itintegration:registry:1' />
    </xs:schema>
  </wsdl:types>
  <wsdl:message name='GetCertificateAdditionsRequest'>
    <wsdl:part name='LogicalAddress' element='itr:LogicalAddress' /> 
    <wsdl:part name='parameters' element='tjsr:GetCertificateAdditions' />
  </wsdl:message>
  <wsdl:message name='GetCertificateAdditionsResponse'>
    <wsdl:part name='parameters' element='tjsr:GetCertificateAdditionsResponse' />
  </wsdl:message>
  <wsdl:portType name='GetCertificateAdditionsResponderInterface'>
    <wsdl:operation name='GetCertificateAdditions'>
      <wsdl:input message='tns:GetCertificateAdditionsRequest' />
      <wsdl:output message='tns:GetCertificateAdditionsResponse' />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name='GetCertificateAdditionsResponderBinding' type='tns:GetCertificateAdditionsResponderInterface'>
    <soap:binding style='document' transport='http://schemas.xmlsoap.org/soap/http' />
    <wsdl:operation name='GetCertificateAdditions'>
      <soap:operation soapAction='urn:riv:clinicalprocess:healthcond:certificate:GetCertificateAdditionsResponder:1:GetCertificateAdditions' style='document' />
      <wsdl:input>
        <soap:header use='literal' message='tns:GetCertificateAdditionsRequest' part='LogicalAddress' />
        <soap:body use='literal' parts='parameters' />
      </wsdl:input>
      <wsdl:output>
        <soap:body use='literal' />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name='GetCertificateAdditionsResponderService'>
    <wsdl:port name='GetCertificateAdditionsResponderPort' binding='tns:GetCertificateAdditionsResponderBinding'>
      <soap:address location='http://tempuri.org' />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>