#!groovy

def buildVersion = "1.0.3"
def projectName = "clinicalprocess-healthcond-monitoring-schemas"

stage('checkout') {
    node {
        util.run { checkout scm }
    }
}

stage('build') {
    node {
        shgradle "--refresh-dependencies :${projectName}:clean :${projectName}:build -DbuildVersion=${buildVersion}"
    }
}

stage('tag and upload') {
    node {
        shgradle ":${projectName}:uploadArchives :${projectName}:tagRelease -DbuildVersion=${buildVersion} -Dintyg.tag.prefix=${projectName}-"
    }
}
