<?xml version="1.0" encoding="UTF-8" ?>
<!--
  ~ Copyright (C) 2016 Inera AB (http://www.inera.se)
  ~
  ~ This file is part of sklintyg (https://github.com/sklintyg).
  ~
  ~ sklintyg is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ sklintyg is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with this program.  If not, see <http://www.gnu.org/licenses/>.
  -->

<wsdl:definitions name='GetMedicalCertificateInteraction'
    xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/'
    xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/'
    xmlns:xs='http://www.w3.org/2001/XMLSchema' xmlns:wsa="http://www.w3.org/2005/08/addressing"
    xmlns:tjsr='urn:riv:clinicalprocess:healthcond:certificate:GetMedicalCertificateResponder:1'
    xmlns:tns='urn:riv:clinicalprocess:healthcond:certificate:GetMedicalCertificate:1:rivtabp21'
    xmlns:itr='urn:riv:itintegration:registry:1' 
    targetNamespace='urn:riv:clinicalprocess:healthcond:certificate:GetMedicalCertificate:1:rivtabp21'>

    <xs:annotation>
        <xs:documentation>
            Tjänsteinteraktionens namn: GetMedicalCertificateInteraction
            Beskrivning:
            Get specified certificate from a care system. Används som ett projektspecifikt kontrakt!
            Revisioner:
            2014-11-20: Initial version (Mats Ekhammar, Callista Enterprise AB)
            Tjänstedomän: clinicalprocess:healthcond:certificate
            Tjänsteinteraktionstyp: Fråga-Svar
            WS-profil: rivtabp21
            Förvaltas av: Sveriges Kommuner och Landsting
        </xs:documentation>
    </xs:annotation>

    <wsdl:types>
        <xs:schema targetNamespace='urn:riv:clinicalprocess:healthcond:certificate:GetMedicalCertificate:1:rivtabp21'>
            <xs:import namespace='urn:riv:clinicalprocess:healthcond:certificate:GetMedicalCertificateResponder:1' schemaLocation='./GetMedicalCertificateResponder_1.0.xsd' />
            <xs:import namespace="urn:riv:itintegration:registry:1" schemaLocation="../../core_components/itintegration_registry_1.0.xsd" />
        </xs:schema>
    </wsdl:types>

    <wsdl:message name='GetMedicalCertificateRequest'>
        <wsdl:part name='LogicalAddress' element='itr:LogicalAddress'>
        </wsdl:part>
        <wsdl:part name='parameters' element='tjsr:GetMedicalCertificateRequest' />
    </wsdl:message>

    <wsdl:message name='GetMedicalCertificateResponse'>
        <wsdl:part name='parameters' element='tjsr:GetMedicalCertificateResponse' />
    </wsdl:message>

    <wsdl:portType name='GetMedicalCertificateResponderInterface'>
        <wsdl:operation name='GetMedicalCertificate'>
            <wsdl:input message='tns:GetMedicalCertificateRequest' />
            <wsdl:output message='tns:GetMedicalCertificateResponse' />
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name='GetMedicalCertificateResponderBinding' type='tns:GetMedicalCertificateResponderInterface'>
        <soap:binding style='document' transport='http://schemas.xmlsoap.org/soap/http' />
        <wsdl:operation name='GetMedicalCertificate'>
            <soap:operation soapAction='urn:riv:clinicalprocess:healthcond:certificate:GetMedicalCertificateResponder:1:GetMedicalCertificate' style='document' />
            <wsdl:input>
                <soap:header use='literal' message='tns:GetMedicalCertificateRequest' part='LogicalAddress' />
                <soap:body use='literal' parts='parameters' />
            </wsdl:input>
            <wsdl:output>
                <soap:body use='literal' />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name='GetMedicalCertificateResponderService'>
        <wsdl:port name='GetMedicalCertificateResponderPort' binding='tns:GetMedicalCertificateResponderBinding'>
            <soap:address location='http://tempuri.org' />
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
