#!groovy

def buildVersion = "2.1.8"
def projectName = "schemas-contract"

stage('checkout') {
    node {
        util.run { checkout scm }
    }
}

stage('build') {
    node {
        shgradle11 "--refresh-dependencies :${projectName}:clean :${projectName}:build -DbuildVersion=${buildVersion} -PcodeQuality"
    }
}

stage('tag and upload') {
    node {
        shgradle11 ":${projectName}:uploadArchives :${projectName}:tagRelease -DbuildVersion=${buildVersion} -Dintyg.tag.prefix=${projectName}-"
    }
}
