#!groovy

def buildVersion = "0.0.1" // "1.0.3"
def projectName = "intyg-infrastructure-directory-privatepractitioner-schemas"
stage('checkout') {
    node {
        util.run { checkout scm }
    }
}

stage('build') {
    node {
        shgradle "--refresh-dependencies :${projectName}:clean :${projectName}:build -DbuildVersion=${buildVersion}"
    }
}

stage('tag and upload') {
    node {
        shgradle ":${projectName}:uploadArchives :${projectName}:tagRelease -DbuildVersion=${buildVersion}"
    }
}
