<?xml version="1.0" encoding="UTF-8" ?>
<!--
  ~ Copyright (C) 2016 Inera AB (http://www.inera.se)
  ~
  ~ This file is part of sklintyg (https://github.com/sklintyg).
  ~
  ~ sklintyg is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ sklintyg is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with this program.  If not, see <http://www.gnu.org/licenses/>.
  -->

<!--
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements. See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership. Sveriges Kommuner och Landsting licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License. You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied. See the License for the
 specific language governing permissions and limitations
 under the License.
 -->		
<wsdl:definitions name='RegisterTSBasInteraction' xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/' xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/' xmlns:xs='http://www.w3.org/2001/XMLSchema' xmlns:tjsr='urn:local:se:intygstjanster:services:RegisterTSBasResponder:1' xmlns:tjsi='urn:local:se:intygstjanster:services:RegisterTSBasInitiator:1' xmlns:tns='urn:local:se:intygstjanster:services:RegisterTSBas:1:rivtabp21' targetNamespace='urn:local:se:intygstjanster:services:RegisterTSBas:1:rivtabp21' xmlns:itr='urn:riv:itintegration:registry:1'>
  <xs:annotation>
    <xs:documentation>
			 Tjänsteinteraktionens namn: RegisterTSBasInteraction
			 Beskrivning: 
			   Registrerar ett TSBas intyg
			 Revisioner: 
			 Tjänstedomän: se:intygstjanster:services
			 Tjänsteinteraktionstyp: Fråga-Svar
			 WS-profil: RIVTABP21
			 Förvaltas av: Sveriges Kommuner och Landsting
			 </xs:documentation>
  </xs:annotation>
  <wsdl:types>
    <xs:schema targetNamespace='urn:local:se:intygstjanster:services:RegisterTSBas:1:rivtabp21'>
      <xs:import schemaLocation='./RegisterTSBasResponder_1.0.xsd' namespace='urn:local:se:intygstjanster:services:RegisterTSBasResponder:1' />
      <xs:import schemaLocation='../../core_components/itintegration_registry_1.0.xsd' namespace='urn:riv:itintegration:registry:1' />
    </xs:schema>
  </wsdl:types>
  <wsdl:message name='RegisterTSBasRequest'>
    <wsdl:part name='LogicalAddress' element='itr:LogicalAddress'>
      <wsdl:documentation>Not used in local contracts</wsdl:documentation>
    </wsdl:part>
    <wsdl:part name='parameters' element='tjsr:RegisterTSBas' />
  </wsdl:message>
  <wsdl:message name='RegisterTSBasResponse'>
    <wsdl:part name='parameters' element='tjsr:RegisterTSBasResponse' />
  </wsdl:message>
  <wsdl:portType name='RegisterTSBasResponderInterface'>
    <wsdl:operation name='RegisterTSBas'>
      <wsdl:input message='tns:RegisterTSBasRequest' />
      <wsdl:output message='tns:RegisterTSBasResponse' />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name='RegisterTSBasResponderBinding' type='tns:RegisterTSBasResponderInterface'>
    <soap:binding style='document' transport='http://schemas.xmlsoap.org/soap/http' />
    <wsdl:operation name='RegisterTSBas'>
      <soap:operation soapAction='urn:local:se:intygstjanster:services:RegisterTSBasResponder:1:RegisterTSBas' style='document' />
      <wsdl:input>
        <soap:header use='literal' message='tns:RegisterTSBasRequest' part='LogicalAddress' />
        <soap:body use='literal' parts='parameters' />
      </wsdl:input>
      <wsdl:output>
        <soap:body use='literal' />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name='RegisterTSBasResponderService'>
    <wsdl:port name='RegisterTSBasResponderPort' binding='tns:RegisterTSBasResponderBinding'>
      <soap:address location='http://tempuri.org' />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
