<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions name='GetSjukpenningInteraction' xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/' xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/' xmlns:xs='http://www.w3.org/2001/XMLSchema' xmlns:tjsr='urn:local:se:intygstjanster:services:fk:GetSjukpenningResponder:1' xmlns:tns='urn:local:se:intygstjanster:services:fk:GetSjukpenning:1:rivtabp21' targetNamespace='urn:local:se:intygstjanster:services:fk:GetSjukpenning:1:rivtabp21' xmlns:itr='urn:riv:itintegration:registry:1'>
    <xs:annotation>
        <xs:documentation>
            Tjänsteinteraktionens namn: GetSjukpenningInteraction
            Beskrivning: 
            Hämtar ett Sjukpenning-intyg
            Revisioner: 
            Tjänstedomän: se:intygstjanster:services:fk
            Tjänsteinteraktionstyp: Fråga-Svar
            WS-profil: RIVTABP21
            Förvaltas av: Sveriges Kommuner och Landsting
        </xs:documentation>
    </xs:annotation>
    <wsdl:types>
        <xs:schema targetNamespace='urn:local:se:intygstjanster:services:fk:GetSjukpenning:1:rivtabp21'>
            <xs:import schemaLocation='./GetSjukpenningResponder_1.0.xsd' namespace='urn:local:se:intygstjanster:services:fk:GetSjukpenningResponder:1' />
            <xs:import schemaLocation='../../core_components/itintegration_registry_1.0.xsd' namespace='urn:riv:itintegration:registry:1' />
        </xs:schema>
    </wsdl:types>
    <wsdl:message name='GetSjukpenningRequest'>
        <wsdl:part name='LogicalAddress' element='itr:LogicalAddress'>
            <wsdl:documentation>Not used in local contracts</wsdl:documentation>
        </wsdl:part>
        <wsdl:part name='parameters' element='tjsr:GetSjukpenning' />
    </wsdl:message>
    <wsdl:message name='GetSjukpenningResponse'>
        <wsdl:part name='parameters' element='tjsr:GetSjukpenningResponse' />
    </wsdl:message>
    <wsdl:portType name='GetSjukpenningResponderInterface'>
        <wsdl:operation name='GetSjukpenning'>
            <wsdl:input message='tns:GetSjukpenningRequest' />
            <wsdl:output message='tns:GetSjukpenningResponse' />
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name='GetSjukpenningResponderBinding' type='tns:GetSjukpenningResponderInterface'>
        <soap:binding style='document' transport='http://schemas.xmlsoap.org/soap/http' />
        <wsdl:operation name='GetSjukpenning'>
            <soap:operation soapAction='urn:local:se:intygstjanster:services:fk:GetSjukpenningResponder:1:GetSjukpenning' style='document' />
            <wsdl:input>
                <soap:header use='literal' message='tns:GetSjukpenningRequest' part='LogicalAddress' />
                <soap:body use='literal' parts='parameters' />
            </wsdl:input>
            <wsdl:output>
                <soap:body use='literal' />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name='GetSjukpenningResponderService'>
        <wsdl:port name='GetSjukpenningResponderPort' binding='tns:GetSjukpenningResponderBinding'>
            <soap:address location='http://tempuri.org' />
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
