<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions name='GetSRSInformationForDiagnosisInteraction' xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/'
                  xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/'
                  xmlns:xs='http://www.w3.org/2001/XMLSchema'
                  xmlns:tjsr='urn:riv:clinicalprocess:healthcond:srs:GetSRSInformationForDiagnosisResponder:1'
                  xmlns:tns='urn:riv:clinicalprocess:healthcond:srs:GetSRSInformationForDiagnosis:1:rivtabp21'
                  targetNamespace='urn:riv:clinicalprocess:healthcond:srs:GetSRSInformationForDiagnosis:1:rivtabp21'>
    <wsdl:types>
        <xs:schema targetNamespace='urn:riv:clinicalprocess:healthcond:srs:GetSRSInformationForDiagnosis:1:rivtabp21'>
            <xs:import schemaLocation='GetSRSInformationForDiagnosisResponder_1.0.xsd'
                       namespace='urn:riv:clinicalprocess:healthcond:srs:GetSRSInformationForDiagnosisResponder:1'/>
        </xs:schema>
    </wsdl:types>

    <wsdl:message name='GetSRSInformationForDiagnosisRequest'>
        <wsdl:part name='parameters' element='tjsr:GetSRSInformationForDiagnosisRequest'/>
    </wsdl:message>

    <wsdl:message name='GetSRSInformationForDiagnosisResponse'>
        <wsdl:part name='parameters' element='tjsr:GetSRSInformationForDiagnosisResponse'/>
    </wsdl:message>

    <wsdl:portType name='GetSRSInformationForDiagnosisResponderInterface'>
        <wsdl:operation name='GetSRSInformationForDiagnosis'>
            <wsdl:input message='tns:GetSRSInformationForDiagnosisRequest'/>
            <wsdl:output message='tns:GetSRSInformationForDiagnosisResponse'/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name='GetSRSInformationForDiagnosisResponderBinding' type='tns:GetSRSInformationForDiagnosisResponderInterface'>
        <soap:binding style='document' transport='http://schemas.xmlsoap.org/soap/http'/>
        <wsdl:operation name='GetSRSInformationForDiagnosis'>
            <soap:operation
                    soapAction='urn:riv:clinicalprocess:healthcond:srs:GetSRSInformationForDiagnosisResponder:1:GetSRSInformationForDiagnosis'
                    style='document'/>
            <wsdl:input>
                <soap:header use='literal' message='tns:GetSRSInformationForDiagnosisRequest' part='LogicalAddress'/>
                <soap:body use='literal' parts='parameters'/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use='literal'/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name='GetSRSInformationForDiagnosisResponderService'>
        <wsdl:port name='GetSRSInformationForDiagnosisResponderPort' binding='tns:GetSRSInformationForDiagnosisResponderBinding'>
            <soap:address location='http://tempuri.org'/>
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>
