#!groovy

def buildVersion = "1.0.24"
def projectName = "intyg-clinicalprocess-healthcond-certificate-schemas"

stage('checkout') {
    node {
        util.run { checkout scm }
    }
}

stage('build') {
    node {
        shgradle11 "--refresh-dependencies :${projectName}:clean :${projectName}:build -DbuildVersion=${buildVersion}"
    }
}

stage('tag and upload') {
    node {
        shgradle11 ":${projectName}:uploadArchives :${projectName}:tagRelease -DbuildVersion=${buildVersion} -Dintyg.tag.prefix=${projectName}-"
    }
}
