<?xml version="1.0" encoding="UTF-8" ?>
<!-- 
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements. See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership. Socialstyrelsen licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License. You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied. See the License for the
 specific language governing permissions and limitations
 under the License.
 -->		
<wsdl:definitions name='GetFmbInteraction' xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/' xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/' xmlns:xs='http://www.w3.org/2001/XMLSchema' xmlns:tjsr='urn:riv:processmanagement:decisionsupport:insurancemedicinedecisionsupport:GetFmbResponder:1' xmlns:tjsi='urn:riv:processmanagement:decisionsupport:insurancemedicinedecisionsupport:GetFmbInitiator:1' xmlns:tns='urn:riv:processmanagement:decisionsupport:insurancemedicinedecisionsupport:GetFmb:1:rivtabp21' targetNamespace='urn:riv:processmanagement:decisionsupport:insurancemedicinedecisionsupport:GetFmb:1:rivtabp21' xmlns:itr='urn:riv:itintegration:registry:1'>
  <xs:annotation>
    <xs:documentation>
			 Tjänsteinteraktionens namn: GetFmbInteraction
			 Beskrivning: 
			    Hämta beslutsunderlag från FMB (Försäkringsmedicinskt beslutsstöd)
			 Revisioner: 
			 Tjänstedomän: processmanagement:decisionsupport:insurancemedicinedecisionsupport
			 Tjänsteinteraktionstyp: Fråga-Svar
			 WS-profil: RIVTABP21
			 Förvaltas av: Socialstyrelsen
			 </xs:documentation>
  </xs:annotation>
  <wsdl:types>
    <xs:schema targetNamespace='urn:riv:processmanagement:decisionsupport:insurancemedicinedecisionsupport:GetFmb:1:rivtabp21'>
      <xs:import schemaLocation='GetFmbResponder_1.0.xsd' namespace='urn:riv:processmanagement:decisionsupport:insurancemedicinedecisionsupport:GetFmbResponder:1' />
      <xs:import schemaLocation='../../core_components/itintegration_registry_1.0.xsd' namespace='urn:riv:itintegration:registry:1' />
    </xs:schema>
  </wsdl:types>
  <wsdl:message name='GetFmbRequest'>
    <wsdl:part name='LogicalAddress' element='itr:LogicalAddress'>
      <wsdl:documentation>Socialstyrelsens organisationsnummer</wsdl:documentation>
    </wsdl:part>
    <wsdl:part name='parameters' element='tjsr:GetFmb' />
  </wsdl:message>
  <wsdl:message name='GetFmbResponse'>
    <wsdl:part name='parameters' element='tjsr:GetFmbResponse' />
  </wsdl:message>
  <wsdl:portType name='GetFmbResponderInterface'>
    <wsdl:operation name='GetFmb'>
      <wsdl:input message='tns:GetFmbRequest' />
      <wsdl:output message='tns:GetFmbResponse' />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name='GetFmbResponderBinding' type='tns:GetFmbResponderInterface'>
    <soap:binding style='document' transport='http://schemas.xmlsoap.org/soap/http' />
    <wsdl:operation name='GetFmb'>
      <soap:operation soapAction='urn:riv:processmanagement:decisionsupport:insurancemedicinedecisionsupport:GetFmbResponder:1:GetFmb' style='document' />
      <wsdl:input>
        <soap:header use='literal' message='tns:GetFmbRequest' part='LogicalAddress' />
        <soap:body use='literal' parts='parameters' />
      </wsdl:input>
      <wsdl:output>
        <soap:body use='literal' />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name='GetFmbResponderService'>
    <wsdl:port name='GetFmbResponderPort' binding='tns:GetFmbResponderBinding'>
      <soap:address location='http://tempuri.org' />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>